### ISSUE TITLE
delete me

### ISSUE THREAD

**Issue by keldLundgaard** [mcocdawc/chemcoord#1]
I get the following ImportError when I try to import the Chemcoord library. Looks like there is a circular import happening.

I have installed Chemcoord via pip.

Please advice

Python 2.7.11 (default, Jan 18 2016, 12:56:57) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chemcoord as cc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/chemcoord/__init__.py", line 12, in <module>
    from . import xyz_functions
  File "/usr/local/lib/python2.7/site-packages/chemcoord/xyz_functions.py", line 9, in <module>
    from . import zmat_functions
  File "/usr/local/lib/python2.7/site-packages/chemcoord/zmat_functions.py", line 8, in <module>
    from . import xyz_functions
ImportError: cannot import name xyz_functions
>>>

**Comment by mcocdawc** [comment]
Unfortanetely it is a python 3.x only package, so could you repeat it with a python 3.x installation please?
But it is definetely a bug in the setup script because you should not be able to install it from python 2.x.
Thank you very much for spotting this bug and sorry for my late answer.

The circular import is necessary for one thing. When the transformation from cartesian coordinates to internal coordinates (and other way around) happens they have to initialize instances of the other class.

**Comment by keldLundgaard** [comment]
Thanks. I discovered that the problem was that I was using python 2 as you suggest, which is why I changed the title to "delete me". Works fine in python 3.
