### ISSUE TITLE
Inconsistent Error?

### ISSUE THREAD

**Issue by emo006** [mcocdawc/chemcoord#3]
I have been running trials converting cartesian coordinate files to internal coordinate files.  I've had success with most files, except for one file.  The formatting of the xyz file appears to be the same as all the others, but I keep getting the error below:

**NameError: name 'row_in_buildlist' is not defined**

Any suggestions for what might be incorrect?

**Comment by mcocdawc** [comment]
Could you append the file? I will have a look. (Not before Thursday)

**Comment by emo006** [comment]
Thanks so much for looking into this.

(I realize this is a .txt file-- I had to change it to upload to git-- so just change it back to a .xyz file if necessary!)

[313nm_struc5_Rw0.24.txt](https://github.com/mcocdawc/chemcoord/files/312513/313nm_struc5_Rw0.24.txt)

**Comment by mcocdawc** [comment]
It is definitely a bug, thank you for spotting!
I will solve it and keep you updated about the new version. (in about a week)

**Comment by mcocdawc** [comment]
The problem is solved and I will update the package soon. Sorry for any inconvenience.
Until this is done, you can install the master branch from the repository:
```
git clone https://github.com/mcocdawc/chemcoord.git
cd chemcoord
python setup.py install --user
```

I would like to use your coordinate file as part of the automated test suite. Is that ok for you?
=====================================================
Note that you also have a very important change for convenience. 
You don't have to use the underlying dataframe for slicing... anymore.
You can get only the hydrogen atoms in molecule:
```
molecule[molecule[:, 'atom'] == 'H', :]
```
Or assign values directly:
```
molecule[1, 'x']  = 42
```
I still have to write a tutorial and documentation for this so I am waiting with the package.

**Comment by mcocdawc** [comment]
You can download version 1.2.0 now.

**Comment by MariP2** [comment]
Hello, 

I have run into the same error, even with  the chemcoord version 1.2.0.
My code:

[convert_to_zmat.pdf](https://github.com/mcocdawc/chemcoord/files/865981/convert_to_zmat.pdf)
I noticed that if I change the first N atom to an Fe atom the conversion works fine.

**Comment by mcocdawc** [comment]
That is indeed worrying. 
Unfortunately I cannot watch into it before two weeks, because I am writing exams. :/
But could you also provide the xyz-file? (You probably have to name it as .txt)

**Comment by MariP2** [comment]
I wasn't starting off from a xyz file, because  I needed a way to easily convert an optimization output to a zmatrix
I'll add the file I was using, but I've also written the coordinates dataframe to an xyz and I'll add that too.
[cartesian_xyz.txt](https://github.com/mcocdawc/chemcoord/files/866151/cartesian_xyz.txt)
[coordinates.txt](https://github.com/mcocdawc/chemcoord/files/866154/coordinates.txt)

**Comment by mcocdawc** [comment]
The reason why both conversions fail, is that certain bonds are not detected.
@MariP2 Is your ruthenium complex already in the relaxed structure? Because perhaps I will increase the van der vaals radius of Ru for detecting bonds.
Nevertheless the conversion should of course work if your structure is split up into fragments.

**Comment by mcocdawc** [comment]
Should work now. Just use the masterbranch
