### ISSUE TITLE
Numba deprecation warning

### ISSUE THREAD

**Issue by ghutchis** [mcocdawc/chemcoord#76]
Running the code with current numba yields the following warnings:

```
/opt/local/mambaforge/lib/python3.9/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
```

**Comment by ghutchis** [comment]
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit

**Comment by mcocdawc** [comment]
Thank you very much for reporting this.
I have to check if I can just change to `numba.jit` or if I relied on the overloading and it requires deeper architectural changes.

**Comment by mcocdawc** [comment]
A proper fix is is doable without architecture changes by following the instructions in your supplied link.

I will not do it yet though, because the use of `isinstance` inside a `jit`ted function is still an experimental feature.
Even in numba 0.57 I get a 
```
 NumbaExperimentalFeatureWarning: Use of isinstance() detected. This is an experimental feature.
```
warning.

I don't want to break with earlier versions, where `generated_jit` is not yet deprecated, while a jitted `isinstance` is not yet supported, if it is not clear that jitted `isinstance` will become the correct replacement.

As soon as a clear successor of `generated_jit` emerges, I will switch.

**Comment by klauspdoll** [comment]
I have numba version 0.59.0 where this now stops with an error:

```
>>> import chemcoord as cc
[...truncated...]
chemcoord/cartesian_coordinates/_cart_transformation.py", line 6, in <module>
   from numba import jit, generated_jit
ImportError: cannot import name 'generated_jit' from 'numba'
```
This is consistent with the information
`Removal took place in version 0.59.0.` 
at  https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit
`isinstance` seems to be okay, the demo at this web page works.

**Comment by mcocdawc** [comment]
Sorry for answering so late to his issue.
I was quite occupied with my defense two days ago.
Now I am free again to do software maintenance and will take care of it.
(In the case that you already fixed it yourself, I am also happily accepting PRs.)

**Comment by mcocdawc** [comment]
Solved now
