### ISSUE TITLE
# Feature to extract all the bonds, bond lengths, bond angles and dihedrals from a given Molecule

### ISSUE THREAD

**Issue by Mayank447** [mcocdawc/chemcoord#84]
Currently the ZMat class doesn't have many a lot of helper functions. It will be nice to have a function to extract all the bonds, their bond lengths, bond angles and dihedrals in the molecule. Another useful helper functions can be to list all the neighbouring atoms to an atom.

I have written some boiler code for the same.

**Comment by mcocdawc** [comment]
Dear Mayank,
Thank you for the interest and the suggestion.
Unfortunately with the information at hand I am against these added features.

On a conceptional level, I don't know how you would obtain the bond length between two arbitrary atoms from a Z-matrix, if that bond length is not contained in the Z-matrix. (Otherwise it is obviously trivial)
So you always would have to convert to cartesian space anyway and `Cartesian`s already have such methods.
The same is true for angles, dihedrals and for listing the coordination sphere of an atom, I think you have to convert to cartesian space anyway.

So the remaining question is. Should there be delegating functions that do the
```python3
zm.get_cartesian().get_bond_lengths(..)
```
for you so that you can write
```python3
zm.get_bond_lengths(..)
```
I am rather against it, because that is very easy to compose yourself.

Looping over all possible bonds, angles and dihedrals is also not hard when combining with the standard library.
For example this code returns you cleanly all possible bond-lengths (accounting for symmetry).
```python3
import itertools

pairs = list(itertools.combinations(zm.index, 2))
(
    pd.DataFrame({'a': [pair[0] for pair in pairs],
                  'b': [pair[1] for pair in pairs],
                  'lengths': m.get_bond_lengths(pairs)})
)
```

The coordination sphere is available via [get_coordination_sphere](https://chemcoord.readthedocs.io/en/v2.0.5/src_Cartesian/src_Cartesian/chemcoord.Cartesian.get_coordination_sphere.html)
and a dictionary of all bonds, is available in [get_bonds](https://chemcoord.readthedocs.io/en/v2.0.5/src_Cartesian/src_Cartesian/chemcoord.Cartesian.get_bonds.html#chemcoord.Cartesian.get_bonds)

**Comment by Mayank447** [comment]
I was talking in the context of an iterator for bonds, bond angles and dihedrals. Also the bond lengths, angles and dihedrals are stored in the .zmat file (2nd, 4th and 6th column respectively). If it was not stored, you can't construct a 3D representation for the molecule and interconversion between other formats like .xyz, .sdf wouldn't have been possible.

**Comment by mcocdawc** [comment]
Could you write an example code assuming everything was there, as you want it?

I think I don't understand what you mean exaclty by _all_ in 

> [...] all the bonds, their bond lengths, bond angles and dihedrals in the molecule [...]

Because you wrote

> [...] Also the bond lengths, angles and dihedrals are stored in the .zmat file [...]

But note that the zmatrix stores only a subset of all possible bond lengths, angles and dihedrals.
The number of all primitive internal coordinates is usually much larger, the number of all possible pairwise distances is then even larger (exactly given by `n * (n - 1) / 2`, where `n` is the number of atoms.)

When you say, that you want to loop over all angles, do you really want to loop over all angles that can be formed by randomly selecting three indices, or should this be at least a primitive internal coordinate, i.e. should these three indices be connected?

**Comment by mcocdawc** [comment]
Dear @Mayank447 ,

may I ask if this is what you had in mind?

```python3
from chemcoord import Cartesian
from typing import Tuple, Iterator


def over_bonds(m: Cartesian) -> Iterator[Tuple[int, int]]:
    "Return an iterator for looping over all bonds"
    D = m.get_bonds()
    for i in sorted(D.keys()):
        for b in sorted(D[i]):
            if i < b:
                yield i, b

def over_angles(m: Cartesian) -> Iterator[Tuple[int, int, int]]:
    "Return an iterator for looping over all angles"
    D = m.get_bonds()
    for i in sorted(D.keys()):
        for b in sorted(D[i]):
            for a in sorted(D[b]):
                if i < a:
                    yield i, b, a

def over_angles(m: Cartesian) -> Iterator[Tuple[int, int, int]]:
    "Return an iterator for looping over all angles"
    D = m.get_bonds()
    for i in sorted(D.keys()):
        for b in sorted(D[i]):
            for a in sorted(D[b]):
                if i < a:
                    yield i, b, a
```

The [get_bonds](https://chemcoord.readthedocs.io/en/v2.0.5/src_Cartesian/chemcoord.Cartesian.html) method gives you the information about all connections in the molecule.

**Comment by mcocdawc** [comment]
closed due to inactivity
